version: '3.4'
services:
  api-service:
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${PORT}
    ports:
      - 3000:${PORT}
    env_file:
      - ./.env
      # - ./.aws # (optional; uncomment if the app uses to aws-sdk)
    volumes:
      - ./:/home/<APP_NAME>
